FROM public.ecr.aws/lts/ubuntu:22.04

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    pandas \
    pydeseq2 \
    matplotlib

COPY source/aggregate_counts.py /opt/scripts/aggregate_counts.py
COPY source/differential_expression.py /opt/scripts/differential_expression.py